### ISSUE TITLE
Ensure Spectrograph switches ports without sleeping

### ISSUE THREAD

**Issue by koseward** [Empyrean-Capstone/Empyrean#109]
Right now, after the message is sent to the spectrograph to change ports, the messaging server simple sleeps and hopes that there was enough time to update the spectrograph before moving on. To change this to ensure completion, there will need to be two functions to make an observation, one that sends all of the parameters to the spectrograph, which, after the spectrograph should send back all of the parameters to the backend.

**Comment by mcauley-penney** [comment]
- Closed here by 34631c13bce223c6dd92afa18cc68e85452ddd84 
- Closed in the Shelyak interface by [603b8ca7c32f91965fb398aee477e51c1beb91d6](https://github.com/Empyrean-Capstone/shelyak_control/commit/603b8ca7c32f91965fb398aee477e51c1beb91d6)
