### ISSUE TITLE
FITS File Handler

### ISSUE THREAD

**Issue by nhatlinh300401** [Empyrean-Capstone/Empyrean#17]
Add the function which handles the FITS file. More specifically, the function will detect the FITS file by checking the beginning of the file (FITS file has a specific header). If the file is not in the FITS type, the function will return an error and announce a message on the website. Otherwise, the function will extract the data below the FITS header.

**Comment by koseward** [comment]
What is the purpose of this function? When is it being used?

**Comment by nhatlinh300401** [comment]
There is a function fits() from package astropy.io which helps users to open and create the file in FITS format. This function will be in the process of preparing a FITS file for users to download from the web page. I don't remember clearly because we mentioned about this before the break so please correct me if there are something I mention above wrong or missing.

**Comment by mcauley-penney** [comment]
The baseline implementation of the file writer(83cdbc84960702a46b6883ab76431357e223246f) creates fits images from the camera input. Closed
