### ISSUE TITLE
Requests from Front-end to Back-end part (!!Team Discussion Need!!)

### ISSUE THREAD

**Issue by nhatlinh300401** [Empyrean-Capstone/Empyrean#18]
Add the function to receive the request from front-end (using ReactJS) to back-end (using Flask). In details, the function at the back-end will receive the information in JSON format from front-end, and extract the useful data from that. The progress is that we successfully creates a really simple ReactJS form which can send the JSON data to Flask. From that, Flask uses the functions from other libraries to extract the JSON format.

**Comment by mcauley-penney** [comment]
See c7a1a7c522a58d4f000dbb41b57403e67327c5e3, 627d535ae5920a61dd4360195614c9de1e1029f4, c7a1a7c522a58d4f000dbb41b57403e67327c5e3
